name: ny_times
description: Build a simple app to hit the NY Times Most Popular Articles API and show a list of articles, that shows details when items on the list are tapped (a typical master/detail app).
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.2.0
  bloc_concurrency: ^0.2.1
  bloc_test: ^9.1.1
  cupertino_icons: ^1.0.2
  core:
    path: packages/core

  cached_network_image: ^3.2.1
  dio: ^5.0.0
  design:
    path: packages/design
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2
  flutter_bounce: ^1.1.0
  flutter_svg: ^2.0.5
  flutter_keyboard_visibility: ^5.2.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_animate: ^4.1.1+1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^6.5.7
  http_parser: ^4.0.1
  json_annotation: ^4.7.0
  mockito: ^5.4.0
  network:
    path: packages/network
  lottie: ^2.3.2
  provider: ^6.0.3
  photo_view: ^0.14.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.8
  responsive_framework: ^0.2.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  built_value_generator: ^8.4.2
  dependency_validator: ^3.0.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
dependency_overrides:
  intl: ^0.18.1
  path_provider_android: 2.0.11

flutter:
  uses-material-design: true

  assets:
    - res/lottie/

flutter_intl:
  enabled: true