name: core
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  logging: ^1.1.0
  flutter_bloc: ^8.1.1
  pub_semver: ^2.1.1
  package_info_plus: ^3.0.1
  shared_preferences: ^2.0.15
  dio: ^5.0.0
  rxdart: ^0.27.3
  bot_toast:
    git:
      ref: master
      url: https://github.com/mr7ssam/botoast
  provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3

